services:
  nginx:
    image: nginx:latest
    ports:
      - 8880:80
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
    container_name: entity_nginx

  app:
    build:
      context: .
      dockerfile: ./_docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
      - db
    container_name: entity_app

  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: entity
      POSTGRES_PASSWORD: iboughtapropertyinegypt
    ports:
      - 8881:5432
    container_name: entity_db
